# [Choice] .NET version: 8.0, 9.0, 10.0 (optional suffix: -bookworm, -noble, ...)
ARG VARIANT="10.0"
FROM mcr.microsoft.com/devcontainers/dotnet:2-${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
